# Generated by Django 4.1.7 on 2023-07-05 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biotech', '0005_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
    ]
